# Generated by Django 4.0.2 on 2022-03-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='First and Last name')),
                ('userType', models.CharField(choices=[('MO', 'Mentor'), ('ME', 'Mentee')], max_length=100, verbose_name='Mentor/Mentee')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100, verbose_name='Gender')),
                ('biography', models.TextField(max_length=2000, verbose_name='Personal Bio')),
                ('photos', models.ImageField(upload_to='', verbose_name='Headshot')),
            ],
        ),
    ]
