# Generated by Django 4.0.2 on 2022-03-26 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.URLField(verbose_name='Professional Portfolio URL (GitHub, LinkedIn, etc.)'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('B', 'Male'), ('I', 'Female'), ('E', 'Other')], max_length=100, verbose_name='Proficiency')),
                ('skillName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile')),
            ],
        ),
    ]
