# Generated by Django 4.0.2 on 2022-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_remove_skill_gender_skill_level_skill_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.URLField(verbose_name='Headshot URL'),
        ),
    ]
