# Generated by Django 4.0.2 on 2022-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_remove_skill_profile_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.EmailField(default='email', max_length=100, verbose_name='Contact Email'),
            preserve_default=False,
        ),
    ]
