# Generated by Django 4.0.2 on 2022-03-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0006_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.EmailField(max_length=100, verbose_name='Contact email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.URLField(null=True, verbose_name='Headshot URL'),
        ),
    ]
